### ISSUE TITLE
Add helper that registers the BearerTokenLoggingContextFilter

### ISSUE THREAD

**Issue by ellisjoe** [palantir/auth-tokens#12]
Many clients register the BearerTokenLoggingContextFilter with a default configuration that looks something like this:

```
env.servlets()
        .addFilter("BearerTokenLoggingContext", BearerTokenLoggingContextFilter.class)
        .addMappingForUrlPatterns(EnumSet.allOf(DispatcherType.class), true, "/*");
```

Some options to make this more convenient are:
1) Add `void install(ServletEnvironment)` to BearerTokenLoggingContextFilter
2) convert BearerTokenLoggingContextFilter from a ServletFilter to a JerseyFilter (make it implement both?), where the latter would show up as `env.jersey().register(BearerTokenLoggingContextFilter.class)`

**Comment by ellisjoe** [comment]
@markelliot

**Comment by markelliot** [comment]
One reason I didn't do these things already was to avoid the dropwizard dep.

**Comment by markelliot** [comment]
(it's currently only a test dep)

**Comment by cihati** [comment]
Given https://github.com/palantir/auth-tokens/pull/29 deprecates `BearerTokenLoggingContextFilter` , I believe this one is safe to close? @markelliot
