### ISSUE TITLE
BearerTokenLoggingContextFilterTests.testBearerTokenLogging is flaky

### ISSUE THREAD

**Issue by ags799** [palantir/auth-tokens#16]
`BearerTokenLoggingContextFilterTests.testBearerTokenLogging` seems to fail non-deterministically on [my PR](https://github.com/palantir/auth-tokens/pull/14). This PR does not impact the test. The test always passes on my machine. Not sure why it's failing on CI.

**Comment by markelliot** [comment]
I suspect this is mostly addressed in #18, so closing this for now.
