### ISSUE TITLE
Please add AuthHeader serializability note to 0.2.4 release notes

### ISSUE THREAD

**Issue by ash211** [palantir/auth-tokens#21]
At https://github.com/palantir/auth-tokens/releases/tag/0.2.4

Proposed language:
- Note that `AuthHeader` is [no longer](https://github.com/palantir/auth-tokens/commit/a8a475aea076ce77eda546af917207967f5d08f0) JSON-serializable as it should be used for `@HeaderParam`s only.  Use `BearerToken` instead which is and should be serializable.

This is technically a backcompat breaking change (I had to change a downstream project to accommodate) so we should at least make note of it in release notes even though we're still in 0.x versions.

cc @pnepywoda

**Comment by EthanLozano** [comment]
Alternatively, could we just revert the change? https://github.com/palantir/auth-tokens/pull/22

**Comment by pnepywoda** [comment]
I don't have edit permissions on the release notes, @markelliot can you make me an admin of this project?

**Comment by markelliot** [comment]
I'm not an administrator of this repo but I updated the release notes.

**Comment by ash211** [comment]
Thanks Mark.  Closing.

I don't see a strong reason to not have AuthHeaders be Jackson-serializable, but will let that discussion happen on another ticket.
