### ISSUE TITLE
ClassCastException calling UnverifiedJsonWebToken of(BearerToken token) 

### ISSUE THREAD

**Issue by mcintyret** [palantir/auth-tokens#31]
using auth-tokens 1.0.1

Executing the following very simple code
```
UnverifiedJsonWebToken jwt = UnverifiedJsonWebToken.of(BearerToken.valueOf(BEARER_TOKEN));
System.out.println(jwt.getUnverifiedUserId());
System.out.println(jwt.getUnverifiedSessionId());
```
Where BEARER_TOKEN is a valid bearer token, I hit this:
```
java.lang.ClassCastException: java.lang.String cannot be cast to [B
    at com.palantir.tokens.auth.UnverifiedJsonWebToken$1.apply(UnverifiedJsonWebToken.java:48)
    at com.google.common.base.Present.transform(Present.java:71)
    at com.palantir.tokens.auth.UnverifiedJsonWebToken.of(UnverifiedJsonWebToken.java:85)
```
I can see in the debugger that the `JsonWebTokenPayload.sid` field that should be an `Optional<byte[]>` has actually been deserialised to an `Optional<String>`, hence the cast exception when something tries to use it.

The decoded segment of the token that the `ObjectMapper` fails to deserialize properly looks like this:
```
{"exp":1490934829,"sid":"DaZqW62fQUe3coo2CL+B7Q==","sub":"595020GOSXOXlxzQBgKJlQ=="}
```

**Comment by pkoenig10** [comment]
I'm unable to reproduce this. The fact that an `Optional<byte[]>` fields was deserialized as a `Optional<String>` object suggest something funky was going on with your classpath or Jackson.
