### ISSUE TITLE
Use ServiceExceptions

### ISSUE THREAD

**Issue by pnepywoda** [palantir/auth-tokens#58]
For where we verify token syntax

**Comment by pkoenig10** [comment]
This is handled by Conjure.
https://github.com/palantir/conjure-java/blob/2776129213d905f8becc0d7f6bf4848f469d5098/conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureAuthorizationExtractor.java#L91-L101
