### ISSUE TITLE
Provide method for getting user id from header

### ISSUE THREAD

**Issue by j-baker** [palantir/auth-tokens#8]
Hey all,
We've found it useful to have code that extracts the 'sub' field from a JWT auth header.
Obviously we can't trust this, but it's useful for logging - being able to say that a certain user made a given request is useful without having to pull in all the complexity of an auth bundle.

Would a `getUserIdInsecure()` method be welcome as part of the AuthHeader or the BearerToken class?

**Comment by pnepywoda** [comment]
@jlz27 @qinfchen what to you think? Is adding logic to the Immutables BearerToken weird?

**Comment by jlzhao27** [comment]
Hmm I think the general idea is fine. The impl will be tricky because the payloads are part of the MP API and I want to consolidate all the token parsing code into 1 location. There is already JWT decoding logic in `multipass-token` so we could move some of that code into here.

**Comment by ellisjoe** [comment]
good to close?
